// After deploying run:  fhevm-forge deploy --contract Counter --chains sepolia
// Then replace the address below with your deployed contract address.
export const CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000" as const;

// Counter.sol ABI — generated by fhevm-forge
export const COUNTER_ABI = [
  {
    name:            "setNumber",
    type:            "function" as const,
    inputs:          [
      { name: "encryptedNumber", type: "bytes32" },
      { name: "inputProof",      type: "bytes"   },
    ],
    outputs:         [],
    stateMutability: "nonpayable" as const,
  },
  {
    name:            "increment",
    type:            "function" as const,
    inputs:          [],
    outputs:         [],
    stateMutability: "nonpayable" as const,
  },
  {
    name:            "getHandle",
    type:            "function" as const,
    inputs:          [],
    outputs:         [{ name: "", type: "bytes32" }],
    stateMutability: "view" as const,
  },
] as const;
