// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { FHE }                from "@fhevm/solidity/lib/FHE.sol";
import { ZamaEthereumConfig } from "@fhevm/solidity/config/ZamaConfig.sol";
import { euint64, externalEuint64 } from "encrypted-types/EncryptedTypes.sol";

/**
 * @title Counter — Minimal FHEVM Example
 * @notice Encrypted counter: the stored value is never exposed in plaintext on-chain.
 *         Mirrors the familiar setNumber / increment interface, encrypted with FHE.
 *         Generated by fhevm-forge. See AGENT.md for development guidelines.
 */
contract Counter is ZamaEthereumConfig {
    euint64 private _number;

    constructor() {
        _number = FHE.asEuint64(0);
        FHE.allowThis(_number);
    }

    /// @notice Set the counter to an encrypted value.
    ///         Caller must supply a ciphertext + ZK input proof from fhevmjs.
    function setNumber(externalEuint64 encryptedNumber, bytes calldata inputProof) external {
        euint64 newNumber = FHE.fromExternal(encryptedNumber, inputProof);
        FHE.allowThis(newNumber);
        _number = newNumber;
        FHE.allowThis(_number);
        FHE.allow(_number, msg.sender);
    }

    /// @notice Increment the counter by 1. No proof needed — 1 is a public constant.
    function increment() external {
        _number = FHE.add(_number, FHE.asEuint64(1));
        FHE.allowThis(_number);
    }

    /// @notice Returns the encrypted handle. Call fhevmjs.reencrypt() off-chain to read the value.
    function getHandle() external view returns (bytes32) {
        return euint64.unwrap(_number);
    }
}
